CrossPlanner/CrossPlanner.Staff/Controllers/MembershipController.cs
using CrossPlanner.Repository.Wrapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using CrossPlanner.Domain.Models;
using Microsoft.EntityFrameworkCore;
using CrossPlanner.Domain.Enums;
using CrossPlanner.Domain.OtherModels;
using Microsoft.Extensions.Options;
using CrossPlanner.Service.Stripe;

namespace CrossPlanner.Staff.Controllers
{
    [Authorize(Roles = "SuperUser,Manager")]
    public class MembershipController : Controller
    {
        private readonly ILogger<MembershipController> _logger;
        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly IOptions<StripeSettings> _stripeSettings;
        private readonly IStripeService _stripeService;
        private const string logPrefix = "Ctlr|Membership";

        public MembershipController(
            ILogger<MembershipController> logger,
            IRepositoryWrapper repositoryWrapper,
            IOptions<StripeSettings> stripeSettings,
            IStripeService stripeService)
        {
            _logger = logger;
            _repositoryWrapper = repositoryWrapper;
            _stripeSettings = stripeSettings;
            _stripeService = stripeService;
        }

        [HttpGet]
        public IActionResult ViewMembership(string applicationUserId)
        {
            Int32.TryParse(User.FindFirst("Affiliate")?.Value, out int affiliateId);
            _logger.LogInformation($"{logPrefix} - Displaying memberships for member with id {applicationUserId} for affiliate with id {affiliateId}");

            var data = _repositoryWrapper.MembershipRepository.GetUserMemberships(affiliateId, applicationUserId);

            return View(data);
        }

        [HttpPut]
        public async Task<IActionResult> CancelMembership(int membershipId)
        {
            _logger.LogInformation($"{logPrefix} - Attempting to cancel membership with id {membershipId}");

            using (var transaction = _repositoryWrapper.BeginTransaction())
            {
                try
                {
                    var membership = _repositoryWrapper.MembershipRepository
                        .FindByCondition(m => m.MembershipId == membershipId)
                        .Include("MembershipPlan")
                        .FirstOrDefault();

                    if (membership == null || string.IsNullOrEmpty(membership.LastPaymentId))
                    {
                        _logger.LogWarning($"{logPrefix} - Unable to cancel membership with id {membershipId} as could not be found");
                        return Json(new { message = "Membership could not be found." });
                    }

                    Int32.TryParse(User.FindFirst("Affiliate")?.Value, out int affiliateId);
                    var affiliate = GetAffiliateById(affiliateId);

                    if (affiliate == null)
                    {
                        _logger.LogError($"{logPrefix} - Could not find affiliate with id {affiliateId}");
                        return Json(new { message = "Unable to cancel membership." });
                    }

                    if (string.IsNullOrEmpty(affiliate.ConnectedAccountId))
                    {
                        _logger.LogError($"{logPrefix} - Affiliate with id {affiliateId} does not have ConnectedAccountId.");
                        return Json(new { message = "Unable to cancel membership." });
                    }

                    decimal refundAmount = CalculateRefundAmount(membership);
                    var processRefund = await _stripeService.RefundCustomer(refundAmount, membership.LastPaymentId, affiliate.ConnectedAccountId);

                    if (processRefund.Success)
                    {
                        membership.IsActive = false;
                        membership.AutoRenew = false;
                        membership.PaymentStatus = PaymentStatus.Refunded;
                        _repositoryWrapper.MembershipRepository.Update(membership);

                        var refund = new Refund
                        {
                            MembershipId = membership.MembershipId,
                            Amount = refundAmount,
                            RefundDate = DateTime.Now,
                            StripeRefundId =processRefund.RefundId,
                        };

                        _repositoryWrapper.RefundRepository.Create(refund);
                        _repositoryWrapper.Save();
                        transaction.Commit();

                        _logger.LogInformation($"{logPrefix} - Membership with id {membershipId} has been successfully canceled");
                        return Json(new { message = "Membership canceled." });
                    }
                    else
                    {
                        _logger.LogError($"{logPrefix} - Failed to cancel membership with id {membershipId }");
                        return Json(new { message = "Unable to cancel membership." });
                    }
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    _logger.LogError($"{logPrefix} - An error occurred while attempting to cancel membership with id {membershipId}: {ex}");
                    return Json(new { message = "An error occurred while canceling membership." });
                }
            }
        }

        private decimal CalculateRefundAmount(Membership model)
        {
            if (model.MembershipPlan.Type == (int)MembershipType.Monthly)
            {
                /*
                    * Calculate the total number of classes allowed over the entire membership period
                    * Determine how many classes have been attended
                    * Calculate the cost per class by dividing the total payment by the total number of classes
                    * Refund the cost for the number of unattended classes
                 */

                return 0;
            }
            else if (model.MembershipPlan.Type == (int)MembershipType.Weekly)
            {
                // Refund is calculated based on the weeks remaining in the membership after cancellation
                int totalWeeks = (model.EndDate ?? DateTime.Now).Subtract(model.StartDate).Days / 7;
                int weeksUsed = DateTime.Now.Subtract(model.StartDate).Days / 7;
                int weeksLeft = totalWeeks - weeksUsed;
                decimal weeklyCost = (decimal)(model.LastPaymentAmount / totalWeeks);

                return weeklyCost * weeksLeft;
            }
            else if (model.MembershipPlan.Type == (int)MembershipType.Unlimited)
            {
                // Refund is calculated based on the total days
                int totalDays = (model.EndDate ?? DateTime.Now).Subtract(model.StartDate).Days;
                int usedDays = DateTime.Now.Subtract(model.StartDate).Days;
                int unusedDays = totalDays - usedDays;
                decimal dailyRate = (decimal)(model.LastPaymentAmount / totalDays);

                return dailyRate * unusedDays;
            }
            else
            {
                _logger.LogWarning($"{logPrefix} - Encountered an unrecognized membership type for membership with id: {model.MembershipId}");
                return 0;
            }
        }

        // Maybe implement the below at a later date

        [HttpGet]
        public IActionResult Index(string q, int page = 1, int pageSize = 25)
        {
            Int32.TryParse(User.FindFirst("Affiliate")?.Value, out int affiliateId);
            _logger.LogInformation($"{logPrefix} - Displaying memberships for affiliate with id {affiliateId}");

            var data = _repositoryWrapper.MembershipRepository.GetAffiliateMemberships(q, affiliateId, page, pageSize);
            var count = _repositoryWrapper.MembershipRepository.GetAffiliateMembershipsCount(q, affiliateId, page, pageSize);

            ViewData["CurrentFilter"] = q;

            // Paging
            ViewData["Page"] = page;
            ViewData["PageSize"] = pageSize;
            ViewData["RecordCount"] = count;
            ViewData["Action"] = "Index";

            return View(data);
        }

        private Affiliate GetAffiliateById(int affiliateId)
        {
            return _repositoryWrapper.AffiliateRepository
                .FindByCondition(a => a.AffiliateId == affiliateId)
                .FirstOrDefault();
        }
    }
}

CrossPlanner/CrossPlanner.Staff/Views/User/Index.cshtml
@model IEnumerable<AffiliateUsersViewModel>
@{
    ViewData["Title"] = "Users";
    var pageSize = 0;

    string linkedToGymSearch = ViewData["LinkedToGymSearch"]?.ToString() ?? "0";
    string emailConfirmedSearch = ViewData["EmailConfirmedSearch"]?.ToString() ?? "0";
    string activeMembershipSearch = ViewData["ActiveMembershipSearch"]?.ToString() ?? "0";
    string roleSearch = ViewData["RoleSearch"]?.ToString() ?? "0";

    if (ViewData["PageSize"] != null && ViewData["RecordCount"] != null)
    {
        pageSize = int.Parse(ViewData["PageSize"].ToString());
    }

    List<SelectListItem> LinkedToGymList = new List<SelectListItem>
    {
        new SelectListItem("Linked to gym", "1"),
        new SelectListItem("Not linked to gym", "2")
    };

    List<SelectListItem> EmailConfirmedList = new List<SelectListItem>
    {
        new SelectListItem("Email Confirmed", "1"),
        new SelectListItem("Email Not Confirmed", "2")
    };

    List<SelectListItem> ActiveMembershipList = new List<SelectListItem>
    {
        new SelectListItem("Active Membership", "1"),
        new SelectListItem("No Active Membership", "2")
    };

    List<SelectListItem> RoleList = new List<SelectListItem>
    {
        new SelectListItem("Coach", "Coach"),
        new SelectListItem("Manager", "Manager"),
        new SelectListItem("Member", "Member"),
        new SelectListItem("SuperUser", "SuperUser"),
    };
}

<form id="filterForm" asp-action="Index" method="get" class="mb-3">
    <div class="card bg-light">
        <div class="card-body">
            <div role="search">
                <div class="row">
                    
                    <div class="col-md-3 mb-4">
                        <label for="linkedToGymSearch">Linked to Gym</label>
                        <select class="form-control" id="linkedToGymSearch" name="linkedToGymSearch">
                            <option value="0">Display All</option>
                            @foreach (var ltg in LinkedToGymList)
                            {
                                if (ltg.Value == linkedToGymSearch)
                                {
                                    <option selected value="@ltg.Value">@ltg.Text</option>
                                }
                                else
                                {
                                    <option value="@ltg.Value">@ltg.Text</option>
                                }
                            }
                        </select>
                    </div>

                    <div class="col-md-3 mb-4">
                        <label for="emailConfirmedSearch">
                            Email Confirmed
                            <i class="fa fa-info-circle" data-bs-toggle="tooltip" title="Filter applies only to users currently linked to your affiliate"></i>
                        </label>
                        <select class="form-control" id="emailConfirmedSearch" name="emailConfirmedSearch">
                            <option value="0">Display All</option>
                            @foreach (var ec in EmailConfirmedList)
                            {
                                if (ec.Value == emailConfirmedSearch)
                                {
                                    <option selected value="@ec.Value">@ec.Text</option>
                                }
                                else
                                {
                                    <option value="@ec.Value">@ec.Text</option>
                                }
                            }
                        </select>
                    </div>

                    <div class="col-md-3 mb-4">
                        <label for="activeMembershipSearch">
                            Active Membership
                            <i class="fa fa-info-circle" data-bs-toggle="tooltip" title="Filter applies only to users currently linked to your affiliate"></i>
                        </label>
                        <select class="form-control" id="activeMembershipSearch" name="activeMembershipSearch">
                            <option value="0">Display All</option>
                            @foreach (var am in ActiveMembershipList)
                            {
                                if(am.Value == activeMembershipSearch)
                                {
                                    <option selected value="@am.Value">@am.Text</option>
                                }
                                else
                                {
                                    <option value="@am.Value">@am.Text</option>
                                }
                            }
                        </select>
                    </div>

                    <div class="col-md-3 mb-4">
                        <label for="roleSearch">
                            Role
                            <i class="fa fa-info-circle" data-bs-toggle="tooltip" title="Filter applies only to users currently linked to your affiliate"></i>
                        </label>
                        <select class="form-control" id="roleSearch" name="roleSearch">
                            <option value="0">Display All</option>
                            @foreach (var r in RoleList)
                            {
                                if (r.Value == roleSearch)
                                {
                                    <option selected value="@r.Value">@r.Text</option>
                                }
                                else
                                {
                                    <option value="@r.Value">@r.Text</option>
                                }
                            }
                        </select>
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-12 mb-4 mb-md-0">
                        <label for="query">Search</label>
                        <i class="fa fa-info-circle" data-bs-toggle="tooltip" title="Filter applies only to name, and email"></i>
                        <div class="input-group mb-3">
                            <input class="form-control" type="text" id="q" name="q" placeholder="Search" value="@ViewData["CurrentFilter"]" id="query">
                            <div class="input-group-lg">
                                <button type="submit" class="btn btn-green"><i class="fa fa-search" aria-hidden="true"></i> Search</button>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <input type="hidden" name="page" value="1" />
                        <input type="hidden" name="pageSize" value="@pageSize" />
                    </div>
                </div>

                <div class="float-right">
                    <button id="add-existing-user" class="btn btn-secondary"><i class="fa fa-plus" aria-hidden="true"></i> Add Existing User</button>
                    <a class="btn btn-secondary" asp-area="Identity" asp-page="/Account/CreateAccount" asp-route-returnController="User"><i class="fas fa-user-plus" aria-hidden="true"></i> Create</a>
                    <button id="clear-filters" class="btn btn-secondary collapse">
                        <i class="fa fa-times" aria-hidden="true"></i> Clear Filters
                    </button>

                </div>
            </div>
        </div>
    </div>
</form>
<br />

@if (Model.Count() > 0)
{
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    Name
                </th>

                <th>
                    Date of Birth
                </th>

                <th>
                    Email
                </th>

                <th>
                    Linked to Gym
                </th>

                <th>
                    Email Confirmed
                </th>

                <th>
                    Active Membership
                </th>

                <th>
                    Role
                </th>

                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.FirstName @item.LastName
                    </td>

                    <td>
                        @item.DateOfBirth.ToShortDateString()
                    </td>

                    <td>
                        @item.Email
                    </td>

                    <td>
                        @if (item.AffiliateUserLink)
                        {
                            <span class="text-success"><i class="fa fa-check"></i></span>
                        }
                        else
                        {
                            <span class="text-danger"><i class="fa fa-times"></i></span>
                        }
                    </td>

                    <td>
                        @* We only make this visible if the user is currently linked to the affiliate *@
                        @if (item.AffiliateUserLink)
                        {
                            @if (item.EmailConfirmed)
                            {
                                <span class="text-success"><i class="fa fa-check"></i></span>
                            }
                            else
                            {
                                <span class="text-danger"><i class="fa fa-times"></i></span>
                            }
                        }
                        else
                        {
                            <span class="text-muted">Not Available</span>
                        }
                    </td>

                    <td>
                        @* We only make this visible if the user is currently linked to the affiliate *@
                        @if (item.AffiliateUserLink)
                        {
                            @if (item.ActiveMembership)
                            {
                                <span class="text-success"><i class="fa fa-check"></i></span>
                            }
                            else
                            {
                                <span class="text-danger"><i class="fa fa-times"></i></span>
                            }
                            
                        }
                        else
                        {
                            <span class="text-muted">Not Available</span>
                        }
                    </td>

                    <td>
                        @* We only make this visible if the user is currently linked to the affiliate *@
                        @if (item.AffiliateUserLink)
                        {
                            @item.RoleName
                        }
                        else
                        {
                            <span class="text-muted">Not Available</span>
                        }
                    </td>

                    <td>
                        <div class="dropdown">
                            <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdown-@item.AspNetUserId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Actions
                            </button>

                            <div class="dropdown-menu" aria-labelledby="dropdown-@item.AspNetUserId">
                                @if (item.AffiliateUserLink && !item.EmailConfirmed)
                                {
                                    <button data-id="@item.AspNetUserId" data-role="@item.RoleName" class="dropdown-item resend-verification"><i class="fa fa-mail-bulk" aria-hidden="true"></i> Resend Verification</button>
                                }

                                @if (item.AffiliateUserLink)
                                {
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/EditAccount" asp-route-applicationUserId="@item.AspNetUserId" asp-route-returnController="User"><i class="fas fa-edit" aria-hidden="true"></i> Edit</a>
                                }

                                @if (!(item.AspNetUserId == User.FindFirstValue(ClaimTypes.NameIdentifier)) && item.AffiliateUserLink && !item.ActiveMembership)
                                {
                                    <button data-id="@item.AspNetUserId" class="dropdown-item deactivate-account"><i class="fa fa-ban" aria-hidden="true"></i> Deactivate Account</button>
                                }

                                @if (item.MembershipHistory)
                                {
                                    <a class="dropdown-item" asp-controller="Membership" asp-action="ViewMembership" asp-route-applicationUserId="@item.AspNetUserId"><i class="fas fa-eye" aria-hidden="true"></i> Membership</a>
                                }
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <partial name="_Pagination" />
}
else
{
    <div class="alert alert-info mt-4 text-center">
        <h4 class="alert-heading">No Users Available</h4>
        <p>There are no users matching your search criteria. Please try adjusting your filters or search terms.</p>
    </div>
}

<partial name="_FeedbackModal" />
<partial name="_UserSelectionModal" />

@section Scripts {
    <script src="~/js/userFilter.js"></script>
    <script src="~/js/userManagement.js"></script>
}

CrossPlanner/CrossPlanner.Staff/Views/User/ReviewUserDetails.cshtml
@model ReactivateUserViewModel
@{
    ViewData["Title"] = "Review User Details";
    var today = DateTime.Now.ToString("yyyy-MM-dd");
}

<div class="row">
    <div class="col-md-12">
        <a asp-action="Index" class="btn btn-sm btn-secondary"><i class="fa fa-chevron-left" aria-hidden="true"></i> Go Back</a>
    </div>
</div>

<div class="d-flex justify-content-center align-items-center">
    <div class="col-md-5">
        <section>

            <form id="createForm" method="post">
                <div class="card bg-light">
                    <div class="card-body">
                        <h3>Review User Details</h3>
                        <hr />

                        <div asp-validation-summary="ModelOnly" class="text-danger" role="alert"></div>
                        <input asp-for="ApplicationUserId" type="hidden" />

                        <div class="form-floating mb-3">
                            <input asp-for="FirstName" id="first-name" class="form-control" aria-required="true" readonly />
                            <label asp-for="FirstName" class="form-label">First Name <span class="required">*</span></label>
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>

                        <div class="form-floating mb-3">
                            <input asp-for="LastName" id="last-name" class="form-control" aria-required="true" readonly />
                            <label asp-for="LastName" class="form-label">Last Name <span class="required">*</span></label>
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>

                        <div class="form-floating mb-3">
                            <input type="date" asp-for="DateOfBirth" id="date-of-birth" class="form-control" aria-required="true" max="@today" readonly />
                            <label asp-for="DateOfBirth" class="form-label">Date Of Birth <span class="required">*</span></label>
                            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                        </div>

                        <div class="form-floating mb-3">
                            <input asp-for="Email" id="email" class="form-control" autocomplete="username" aria-required="true" readonly />
                            <label asp-for="Email" class="form-label">Email <span class="required">*</span></label>
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>

                        <div class="form-floating mb-3">
                            <select asp-for="Role" id="role" class="form-control" aria-required="true">
                                <option disabled selected value="">-- Select user role --</option>
                                @foreach (var userRole in Model.Roles)
                                {
                                    <option value="@userRole.Value">@userRole.Text</option>
                                }
                            </select>
                            <label asp-for="Role" class="form-label">Role <span class="required">*</span></label>
                            <span asp-validation-for="Role" class="text-danger"></span>
                        </div>

                        <div class="mb-1">
                            <button id="create-submit" type="submit" class="w-100 btn btn-lg btn-green" disabled><i class="fa fa-user-check" aria-hidden="true"></i> Reactivate User Account</button>
                        </div>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/createAccount.js"></script>
}