CrossPlanner/CrossPlanner.Member/Controllers/ScheduledClassController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using CrossPlanner.Repository.Wrapper;
using CrossPlanner.Domain.OtherModels;
using CrossPlanner.Domain.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using CrossPlanner.Domain.Enums;

namespace CrossPlanner.Member.Controllers
{
    [Authorize(Roles = "Member")]
    public class ScheduledClassController : Controller
    {
        private readonly ILogger<ScheduledClassController> _logger;
        private readonly IRepositoryWrapper _repositoryWrapper;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private const string logPrefix = "Ctlr|ScheduledClass";

        public ScheduledClassController(
            ILogger<ScheduledClassController> logger,
            IRepositoryWrapper repositoryWrapper,
            SignInManager<ApplicationUser> signInManager)
        {
            _logger = logger;
            _repositoryWrapper = repositoryWrapper;
            _signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index(DateTime? date)
        {
            Int32.TryParse(User.FindFirst("Affiliate")?.Value, out int affiliateId);
            var memberId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var selectedDate = date ?? DateTime.Today;

            if (affiliateId == 0 || string.IsNullOrEmpty(memberId))
            {
                _logger.LogWarning($"{logPrefix} - Redirecting user to login page as affiliateId was {affiliateId} and memberId was {memberId}");
                await _signInManager.SignOutAsync();
                return RedirectToPage("/Account/Login", new { area = "Identity" } );
            }

            _logger.LogInformation($"{logPrefix} - Attempting to display scheduled classes for affiliate with id {affiliateId} on {selectedDate.ToShortDateString()}");

            var existingMembership = _repositoryWrapper.MembershipRepository.GetMembershipByAffiliateMemberId(affiliateId, memberId);
            if (existingMembership == null)
            {
                TempData["MembershipMessage"] = "You do not have an active membership. Please activate a membership to book into classes.";
            }

            var scheduledClassDetails = _repositoryWrapper.ScheduledClassRepository.GetAffiliateScheduledClassByDateMember(affiliateId, selectedDate, memberId);

            var viewModel = new DailyScheduleViewModel
            {
                SelectedDate = selectedDate,
                ScheduledClassDetails = scheduledClassDetails.ToList()
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult WhosComing(int scheduledClassId)
        {
            _logger.LogInformation($"{logPrefix} - Attempting to display who's coming to scheduled class with id {scheduledClassId}");

            var scheduledClass = _repositoryWrapper.ScheduledClassRepository.GetScheduledClassById(scheduledClassId);
            if (scheduledClass == null)
            {
                _logger.LogWarning($"{logPrefix} - Scheduled class with id {scheduledClassId} not found.");
                return NotFound();
            }

            var attendees = _repositoryWrapper.ScheduledClassReservationRepository.GetClassAttendeesByScheduledClassId(scheduledClassId);

            var viewModel = new WhosComingViewModel
            {
                ScheduledClassId = scheduledClassId,
                ClassName = scheduledClass.ClassType.Title,
                StartDateTime = scheduledClass.StartDateTime,
                EndDateTime = scheduledClass.EndDateTime,
                Attendees = attendees,
            };

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ReserveScheduledClass(int scheduledClassId)
        {
            try
            {
                Int32.TryParse(User.FindFirst("Affiliate")?.Value, out int affiliateId);
                var memberId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                
                if (affiliateId == 0 || string.IsNullOrEmpty(memberId))
                {
                    _logger.LogWarning($"{logPrefix} - Redirecting user to login page as affiliateId was {affiliateId} and memberId was {memberId}");
                    await _signInManager.SignOutAsync();
                    return RedirectToPage("/Account/Login", new { area = "Identity" });
                }
                
                _logger.LogInformation($"{logPrefix} - Member with id {memberId} is attempting to reserve scheduled class with id {scheduledClassId}");
                
                var existingMembership = _repositoryWrapper.MembershipRepository.GetMembershipByAffiliateMemberId(affiliateId, memberId);
                if (existingMembership == null)
                {
                    _logger.LogWarning($"{logPrefix} - Unable to reserve scheduled class with id {scheduledClassId} as member with id {memberId} does not have an active membership");
                    return Json(new { message = "You do not have an active membership." });
                }
                
                var scheduledClass = _repositoryWrapper.ScheduledClassRepository.GetScheduledClassByIdSP(scheduledClassId);
                if (scheduledClass == null)
                {
                    _logger.LogWarning($"{logPrefix} - Unable to reserve scheduled class with id {scheduledClassId} as could not be found.");
                    return Json(new { message = "Class not found." });
                }

                if (scheduledClass.StartDateTime > existingMembership.EndDate)
                {
                    // This rule will change when we implement auto renew we will implement this at a later date
                    _logger.LogWarning($"{logPrefix} - membership with id {existingMembership.MembershipId} will not be active for the scheduled class on {scheduledClass.StartDateTime} due to the membership's end date {existingMembership.EndDate}.");
                    return Json(new { message = "Your membership will not be active at the time of the scheduled class." });
                }

                if (string.Equals(Enum.GetName(typeof(MembershipType), existingMembership.MembershipPlan.Type), Enum.GetName(MembershipType.Weekly)))
                {
                    var startOfWeek = scheduledClass.StartDateTime.AddDays(-(int)scheduledClass.StartDateTime.DayOfWeek).Date;
                    var endOfWeek = startOfWeek.AddDays(6).AddHours(23).AddMinutes(59).AddSeconds(59);

                    // Adjust start and end of week based on membership start and end dates
                    if (existingMembership.StartDate > startOfWeek)
                    {
                        startOfWeek = existingMembership.StartDate;
                    }

                    if (existingMembership.EndDate < endOfWeek)
                    {
                        endOfWeek = (DateTime)existingMembership.EndDate;
                    }

                    var activeDaysThisWeek = (endOfWeek - startOfWeek).Days + 1; // +1 because both start and end days are inclusive

                    // Calculate the adjusted number of classes allowed for this week
                    var maxClassesThisWeek = Math.Ceiling((decimal)((decimal)activeDaysThisWeek / 7 * existingMembership.MembershipPlan.NumberOfClasses));

                    var classesThisWeek = _repositoryWrapper.ScheduledClassReservationRepository.GetMemberClassAttendanceByWeek(existingMembership.MembershipId, startOfWeek, endOfWeek);

                    if (classesThisWeek >= maxClassesThisWeek)
                    {
                        _logger.LogWarning($"{logPrefix} - Member with id {memberId} has reached their weekly class limit. Unable to reserve scheduled class with id {scheduledClassId}.");
                        return Json(new { message = $"You have reached your weekly limit for class reservations: {classesThisWeek} out of {maxClassesThisWeek} classes reserved." });
                    }
                }
                else if (string.Equals(Enum.GetName(typeof(MembershipType), existingMembership.MembershipPlan.Type), Enum.GetName(MembershipType.Monthly)))
                {
                    var classAttendancewithMembership = _repositoryWrapper.ScheduledClassReservationRepository.GetMemberClassAttendanceByMembershipId(existingMembership.MembershipId);

                    if (classAttendancewithMembership >= existingMembership.MembershipPlan.NumberOfClasses)
                    {
                        _logger.LogWarning($"{logPrefix} - Member with id {memberId} has reached their monthly class limit. Unable to reserve scheduled class with id {scheduledClassId}.");
                        return Json(new { message = $"You have reached your monthly limit for class reservations: {existingMembership.MembershipPlan.NumberOfClasses} classes over {existingMembership.MembershipPlan.NumberOfMonths} months." });
                    }
                }

                if (scheduledClass.Capacity != null && scheduledClass.ReservationsCount >= scheduledClass.Capacity)
                {
                    _logger.LogWarning($"{logPrefix} - Unable to reserve scheduled class with id {scheduledClassId} as it has reached its capacity.");
                    return Json(new { message = "Class is full." });
                }

                var scheduledClassReservation = new ScheduledClassReservation
                {
                    MembershipId = existingMembership.MembershipId,
                    ScheduledClassId = scheduledClassId,
                    ReservationDate = DateTime.Now,
                };

                _repositoryWrapper.ScheduledClassReservationRepository.Create(scheduledClassReservation);
                await _repositoryWrapper.SaveAsync();

CrossPlanner/CrossPlanner.Member/Views/Shared/_AffiliateNamePartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager

<div class="navbar-text text-center flex-grow-1">
    @if (SignInManager.IsSignedIn(User))
    {
        <span class="h3 affiliate-name">@User.FindFirst("AffiliateName")?.Value</span>
    }
</div>

CrossPlanner/CrossPlanner.Member/Views/Shared/_DatePickerModal.cshtml
<div class="modal fade" id="datePickerModal" tabindex="-1" aria-labelledby="datePickerModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="datePickerModalLabel">Select a Date</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <input type="date" id="datepicker" class="form-control" placeholder="Pick a date" />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="goToDate">Go</button>
            </div>
        </div>
    </div>
</div>

CrossPlanner/CrossPlanner.Member/Views/Shared/_FeedbackModal.cshtml
<div class="modal" id="feedbackModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 id="feedbackModalTitle" class="modal-title"></h5>
                <button type="button" class="btn btn-sm btn-danger" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div id="feedbackModalBody" class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> Close</button>
            </div>
        </div>
    </div>
</div>

CrossPlanner/CrossPlanner.Member/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrossPlanner.Member</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrossPlanner.Member.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid d-flex justify-content-between align-items-center">
                <a class="navbar-brand" asp-area="" asp-controller="ScheduledClass" asp-action="Index">
                    <img src="/images/MainLogo.png" alt="Cross Planner Main Logo" class="main-logo" />
                </a>
                
                <div class="navbar-text text-center flex-grow-1">
                    <partial name="_AffiliateNamePartial" />
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CrossPlanner.Member - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CrossPlanner/CrossPlanner.Member/Views/Shared/_Menu.cshtml
@{
    var steps = ViewData["Steps"] as LinkedList<StepViewModel>;
    int stepNumber = 0;
    var isDisabled = false;
    var currentStep = (StepViewModel)ViewData["CurrentStep"];
}

<div class="list-group">
    @if (steps != null)
    {
        foreach (var step in steps)
        {
            stepNumber++;

            var isActive = currentStep.Equals(step);

            var activeClass = isActive ? " active" : string.Empty;
            var disabledClass = isDisabled ? " disabled" : string.Empty;
            string linkClass = $"list-group-item list-group-item-action{activeClass}{disabledClass}";

            if (!isDisabled)
            {
                if (isActive)
                {
                    <a class="@linkClass" asp-action="@step.Name" asp-route-membershipId="@ViewData["MembershipId"]">
                        @($"{stepNumber}. {step.Title}")
                    </a>

                    isDisabled = true;
                }
                else
                {
                    <a class="@linkClass" asp-action="@step.Name" asp-route-membershipId="@ViewData["MembershipId"]">
                        <i class="fas fa-fw fa-check" aria-hidden="true"></i>
                        <span>@($"{stepNumber}. {step.Title}")</span>
                    </a>
                }
            }
            else
            {
                <span class="@linkClass">@($"{stepNumber}. {step.Title}")</span>
            }
        }
    }
</div>

CrossPlanner/CrossPlanner.Member/Views/Shared/_Progress.cshtml
@{
    var steps = ViewData["Steps"] as LinkedList<StepViewModel>;
    decimal totalSteps = steps.Count;
    int stepNumber = (int)ViewData["CurrentStepNumber"];
    var stepPercent = Math.Round((stepNumber / totalSteps) * 100);
}

@functions {
    static string WritePercentageWidth(decimal percent)
    {
        return $"width: {percent}%";
    }
}

<div class="progress-wrapper">
    <span id="menustep">Step @stepNumber of @totalSteps steps</span>
    <div class="progress mb-3">
        <div class="progress-bar" role="progressbar" style="@WritePercentageWidth(stepPercent)" aria-valuenow="@stepPercent" aria-valuemin="0" aria-valuemax="100">
            @stepPercent% Complete
        </div>
    </div>
</div>

CrossPlanner/CrossPlanner.Member/Views/Shared/_PurchaseLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrossPlanner.Member</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrossPlanner.Member.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrossPlanner.Member</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderSection("Progress", required: false)
            <div class="row">

                <div class="col-md-3">
                    @RenderSection("Menu", required: false)
                </div>

                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CrossPlanner.Member - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>